[cubi.metadata]
pid = "undefined"
version = "1.3.2"

[cubi.workflow]
pid = "https://github.com/core-unit-bioinformatics/workflow-smk-assembly-evaluation"
name = "assembly-evaluation"
version = "v1.1-ptyp"

[cubi.workflow.template]
pid = "https://github.com/core-unit-bioinformatics/template-snakemake"
system = "smk"
version = "1.2.0"

[tool.black]
line-length = 88

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.messages_control]
disable=[
  "logging-fstring-interpolation",
  "useless-return",
  "missing-module-docstring"
]

[tool.isort]
profile = "black"
