#!/usr/bin/bash

mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/statistics
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.ebv.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.ebv_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.rdna.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.rdna.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.haplotype1.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.hap1.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.unassigned.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.unassigned.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.haplotype2.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.hap2.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.mito.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.mito_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.mito.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.mito.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.ebv.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.ebv.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.disconnected.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.disconnected.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00733.ps-sseq.wd/assembly.rdna.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/sequences/HG00733.ps-sseq.verkko.rdna_repr.fasta
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/statistics
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.ebv.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.ebv_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.rdna.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.rdna.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.haplotype1.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.hap1.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.unassigned.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.unassigned.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.haplotype2.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.hap2.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.mito.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.mito_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.mito.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.mito.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.ebv.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.ebv.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.disconnected.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.disconnected.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/NA21487.ps-sseq.wd/assembly.rdna.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/sequences/NA21487.ps-sseq.verkko.rdna_repr.fasta
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/statistics
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.ebv.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.ebv_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.rdna.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.rdna.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.haplotype1.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.hap1.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.unassigned.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.unassigned.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.haplotype2.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.hap2.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.mito.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.mito_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.mito.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.mito.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.ebv.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.ebv.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.disconnected.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.disconnected.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02666.ps-sseq.wd/assembly.rdna.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/sequences/HG02666.ps-sseq.verkko.rdna_repr.fasta
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/statistics
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.ebv.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.ebv_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.rdna.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.rdna.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.haplotype1.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.hap1.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.unassigned.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.unassigned.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.haplotype2.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.hap2.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.mito.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.mito_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.mito.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.mito.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.ebv.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.ebv.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.disconnected.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.disconnected.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG02953.ps-sseq.wd/assembly.rdna.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/sequences/HG02953.ps-sseq.verkko.rdna_repr.fasta
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences
mkdir -p /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/statistics
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.ebv.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.ebv_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.rdna.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.rdna.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.haplotype1.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.hap1.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.unassigned.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.unassigned.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.haplotype2.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.hap2.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.mito.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.mito_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.mito.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.mito.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.ebv.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.ebv.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.disconnected.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.disconnected.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/proc/assemblies/verkko/HG00171.ps-sseq.wd/assembly.rdna.exemplar.fasta /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/sequences/HG00171.ps-sseq.verkko.rdna_repr.fasta
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02953.ps-sseq.verkko-asm-hap1.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/statistics/HG02953.ps-sseq.verkko-asm-hap1.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02953.ps-sseq.verkko-unassigned.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/statistics/HG02953.ps-sseq.verkko-unassigned.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00733.ps-sseq.verkko-asm-hap1.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/statistics/HG00733.ps-sseq.verkko-asm-hap1.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00171.ps-sseq.verkko-unassigned.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/statistics/HG00171.ps-sseq.verkko-unassigned.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00733.ps-sseq.verkko-unassigned.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/statistics/HG00733.ps-sseq.verkko-unassigned.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02666.ps-sseq.verkko-rdna.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/statistics/HG02666.ps-sseq.verkko-rdna.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00171.ps-sseq.verkko-asm-hap2.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/statistics/HG00171.ps-sseq.verkko-asm-hap2.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/NA21487.ps-sseq.verkko-rdna.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/statistics/NA21487.ps-sseq.verkko-rdna.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/NA21487.ps-sseq.verkko-disconnected.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/statistics/NA21487.ps-sseq.verkko-disconnected.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00171.ps-sseq.verkko-asm-hap1.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/statistics/HG00171.ps-sseq.verkko-asm-hap1.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02666.ps-sseq.verkko-unassigned.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/statistics/HG02666.ps-sseq.verkko-unassigned.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02666.ps-sseq.verkko-disconnected.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/statistics/HG02666.ps-sseq.verkko-disconnected.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/NA21487.ps-sseq.verkko-asm-hap1.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/statistics/NA21487.ps-sseq.verkko-asm-hap1.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/NA21487.ps-sseq.verkko-asm-hap2.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/statistics/NA21487.ps-sseq.verkko-asm-hap2.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02953.ps-sseq.verkko-rdna.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/statistics/HG02953.ps-sseq.verkko-rdna.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02953.ps-sseq.verkko-disconnected.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/statistics/HG02953.ps-sseq.verkko-disconnected.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00171.ps-sseq.verkko-disconnected.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/statistics/HG00171.ps-sseq.verkko-disconnected.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00171.ps-sseq.verkko-rdna.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00171/statistics/HG00171.ps-sseq.verkko-rdna.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02666.ps-sseq.verkko-asm-hap2.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/statistics/HG02666.ps-sseq.verkko-asm-hap2.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02953.ps-sseq.verkko-asm-hap2.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02953/statistics/HG02953.ps-sseq.verkko-asm-hap2.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00733.ps-sseq.verkko-disconnected.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/statistics/HG00733.ps-sseq.verkko-disconnected.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/NA21487.ps-sseq.verkko-unassigned.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/NA21487/statistics/NA21487.ps-sseq.verkko-unassigned.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00733.ps-sseq.verkko-rdna.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/statistics/HG00733.ps-sseq.verkko-rdna.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG00733.ps-sseq.verkko-asm-hap2.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG00733/statistics/HG00733.ps-sseq.verkko-asm-hap2.summary.tsv
rsync --progress --checksum /gpfs/project/projects/medbioinf/projects/assemblies/hybrids/verkko/wd/results/statistics/assemblies/HG02666.ps-sseq.verkko-asm-hap1.summary.tsv /gpfs/project/projects/medbioinf/data/00_RESTRUCTURE/shares/globus/outgoing/hgsvc/ebi_upload/20230711_verkko_pilot/HG02666/statistics/HG02666.ps-sseq.verkko-asm-hap1.summary.tsv
